### PR TITLE
feat(pod): `shareProcessNamespace`

### PR DESCRIPTION
**Pull request by chensjlv**
add shareProcessNamespace to pod spec. Cannot find it anywhere.

https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/

### CODE REVIEW

**Review by iliapolo — APPROVED** [review]
Thanks!

**Comment by iliapolo** [comment]
Please [allow updates from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) or update the PR manually

**Comment by chensjlv** [comment]
> Please [allow updates from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) or update the PR manually

weird, I don't see the option

**Comment by chensjlv** [comment]
> Please [allow updates from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) or update the PR manually

Seems like it is not an available option for an arg account. Do you want me to create a new PR? Or what do you want me to change?

https://github.com/orgs/community/discussions/5634 😮‍💨

**Comment by iliapolo** [comment]
@chensjlv The "allow update from maintainers" option allows us to do automatic updates from main as well as automatic snapshot updates. In case this isn't allowed, you need to rebase/merge from main manually, and run `yarn build` to regenerate the snapshots. Once the build passes and the code is up to date with main, the PR will merge. 

Currently, the build is failing on a snapshot diff:

```console
diff --git a/test/__snapshots__/container.test.ts.snap b/test/__snapshots__/container.test.ts.snap
index cc078f2..ee03dfa [10](https://github.com/cdk8s-team/cdk8s-plus/actions/runs/10117438309/job/28010509059?pr=3674#step:8:11)0644
--- a/test/__snapshots__/container.test.ts.snap
+++ b/test/__snapshots__/container.test.ts.snap
@@ -68,6 +68,7 @@ Array [
         "runAsNonRoot": true,
       },
       "setHostnameAsFQDN": false,
+      "shareProcessNamespace": false,
       "terminationGracePeriodSeconds": 30,
     },
   }
```

**Pull request closed without merging**
