### PR TITLE
feat(pod): allow passing an existing secret to `dockerRegistryAuth`

### LINKED ISSUE #1784: Allow passing an existing secret as `dockerRegistryAuth`
### Description of the feature or enhancement:

Allow this:

```ts
const registrySecret = kplus.Secret.fromSecretName(this, 'RegistrySecret', 'scw-registry-secret')

new kplus.Pod(chart, 'Pod', {
  containers: [{ image: 'image' }],
  dockerRegistryAuth: registrySecret,
});
```

Currently it is not supported because `dockerRegistryAuth` accepts a `DockerConfigSecret` only.

### Use Case:

Many times secrets are defined externally from the cdk8s application, and need to be referenced by other resources.

### Proposed Solution:

Change `dockerRegistryAuth` to accept an `ISecret`

### Other:

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

### PR DESCRIPTION
**Pull request by iliapolo**
Fixes https://github.com/cdk8s-team/cdk8s-plus/issues/1784

### CODE REVIEW

**Review by vinayak-kukreja — APPROVED** [review]

**Comment by iliapolo** [comment]
## ⚪ Backport skipped
The pull request was not backported as there were no branches to backport to. If this is a mistake, please apply the desired version labels or run the backport tool manually.

### Manual backport
To create the backport manually run:
```
backport --pr 1791
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by iliapolo** [comment]
## 💔 Backport failed
The pull request could not be backported due to the following error:
`The branch "k8s-k8s-25/main/main" does not exist`

### Manual backport
To create the backport manually run:
```
backport --pr 1791
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by iliapolo** [comment]
## 💔 Backport failed
The pull request could not be backported due to the following error:
`Refusing to clone repo into "/var/folders/mb/5zx1h88x2891nhk4qpr6_zc8jcqzm6/T/tmp.2A5zskU6" when current working directory is "/private/var/folders/mb/5zx1h88x2891nhk4qpr6_zc8jcqzm6/T/tmp.2A5zskU6". Please change backport directory via `--dir` option or run backport from another location`

### Manual backport
To create the backport manually run:
```
backport --pr 1791
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by iliapolo** [comment]
## 💔 Backport failed
The pull request could not be backported due to the following error:
`Refusing to clone repo into "/var/folders/mb/5zx1h88x2891nhk4qpr6_zc8jcqzm6/T/tmp.HNsAYR2o" when current working directory is "/private/var/folders/mb/5zx1h88x2891nhk4qpr6_zc8jcqzm6/T/tmp.HNsAYR2o". Please change backport directory via `--dir` option or run backport from another location`

### Manual backport
To create the backport manually run:
```
backport --pr 1791
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by iliapolo** [comment]
## 💔 Backport failed
The pull request could not be backported due to the following error:
`Refusing to clone repo into "/tmp/.backport2" when current working directory is "/private/tmp/.backport2". Please change backport directory via `--dir` option or run backport from another location`

### Manual backport
To create the backport manually run:
```
backport --pr 1791
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by iliapolo** [comment]
## 💔 Backport failed
The pull request could not be backported due to the following error:
`The branch "k8s-k8s-25/main/main" does not exist`

### Manual backport
To create the backport manually run:
```
backport --pr 1791
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by iliapolo** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|k8s-25/main|Cherrypick failed because the selected commit (9e2632f6) is empty. It looks like the commit was already backported in https://github.com/cdk8s-team/cdk8s-plus/pull/1800|

### Manual backport
To create the backport manually run:
```
backport --pr 1791
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
