### PR TITLE
feat(deployment): add ClusterIP option to DeploymentExposeViaServiceOptions

### LINKED ISSUE #938: Add ClusterIP option to DeploymentExposeViaServiceOptions
Currently we can't specify `ClusterIP` option for `deployment.exposeViaService()`. Attempted fix added.

### PR DESCRIPTION
**Pull request by ulutinquity**
Fixes #938

### CODE REVIEW

**Review by iliapolo — CHANGES_REQUESTED** [review]
@ulutinquity Thanks! Can you please also add a unit test?

**Comment by iliapolo** [comment]
@ulutinquity Are you still available to pick this up?

**Comment by ryparker** [comment]
FYI there's now a v25 branch, I'd consider changing the target to v25 and adding the `backport-to-k8s-24/main` label.

**Comment by iliapolo** [comment]
Closing this due to inactivity. @ulutinquity feel free to pick this back up whenever you like 👍

**Pull request closed without merging**
