### PR TITLE
fix(container): enhance Capability enum with ALL cap

### PR DESCRIPTION
**Pull request by serhatcetinkaya**
Fixes #3817 by enhancing Capability enum.

It is possible to drop/add all capabilities by using `ALL` instead of explicitly giving all caps:

```yaml
securityContext:
  capabilities:
    drop:
      - ALL
    add: [“NET_ADMIN”]
```

### CODE REVIEW

**Comment by serhatcetinkaya** [comment]
not really a fix, but adding missing part

**Comment by serhatcetinkaya** [comment]
@iliapolo hello :) did you have any chance to take a look at this ?

**Review by iliapolo — APPROVED** [review]

**Comment by iliapolo** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|k8s-28/main|[](https://github.com/cdk8s-team/cdk8s-plus/pull/4274)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by iliapolo** [comment]
## 💔 All backports failed

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|k8s-28/main|Cherrypick failed because the selected commit (0d395b82) is empty. It looks like the commit was already backported in https://github.com/cdk8s-team/cdk8s-plus/pull/4274|

### Manual backport
To create the backport manually run:
```
backport --pr 4064
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
